---
title: "Lab1 DW AS"
author: "Andrea Soto"
date: "2024-08-05"
output: rmarkdown :: github_document
---

```{r}
library(readxl)
library(openxlsx)
library(dplyr)
library(tidyverse)
##Importar todos los datos de excel 
##Definir la unicación del archivo 
setwd("C:\\Users\\Andrea Soto Gonzalez\\Desktop\\PROGRAMAS DE DATA\\Lab1")

 
##leer todos los archivos de excel dentro de la carpeta que contengan al final -2023
files = list.files(pattern = "*-2023")

##funcion de para leer los archivos sin su fila de nombres puesto a que todos poseen el mismo 
##Funcion para extraer la fecha de la creación del archivo 
ASNFilas <-function(file){
  data<- read_xlsx(file, skip = 1)
  Fecha_archivo = file.info(file)$ctime
  data = data%>%
   mutate(Fecha_archivo = Fecha_archivo)
  return(data)
  
}


#Todos los archivos tienen el mismo nombre de columnas, por lo que se lo establecemos a la tabla combinada 
##aplicar a todos los archivos correspondientes la lectura, con bind_rows se hacen las observaciones por filas 
TABLA_COMBINADA = lapply(files , ASNFilas) %>% bind_rows()

##Necesitamos que la nueva tabla tenga nombres de columnas por lo que leemos la del primer archivo
headers = read_xlsx(files[1], n_max = 0) %>% names()

#Se asignan al nuevo dataframe 
colnames(TABLA_COMBINADA) <- c(headers,"Fecha del archivo")

#Calculamos la moda de mis vectores de interés 
#incorporamos los paqueres y libreria necesaria, donde tenemos la función Mode dentro de los paquetes 
install.packages("modeest")
library(modeest)
MODCOL = TABLA_COMBINADA %>% select(
  PILOTO,
  UBICACION,
  UNIDAD
)
# Calcular la moda 
moda <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

# Lista de vectores 
lista_vectores <- list(
  c(1, 1, 1, 7, 2, 7),
  c(6, 6, 9, 8, 7, 6),
  c(90, 1, 1, 1, 10, 11)
)

# Moda por vectores 
modas <- lapply(lista_vectores, moda)

# Mostrar las modas
modas 



#ver la tabla combinada 
print(head(TABLA_COMBINADA))

# Imprimir el data frame con las modas 
print(DFMODAS)

##Se guaran los registros en un archivo de excel 
write.xlsx(TABLA_COMBINADA10, "Tabla_combinada_10.xlsx", rownames = FALSE )


```


```{r}
## EJERCICIO 3
data <- read_delim("C:\\Users\\Andrea Soto Gonzalez\\Desktop\\PROGRAMAS DE DATA\\INE_PARQUE_VEHICULAR_080219.txt", delim = "|")

head(data)
```

